# Create "installable" preview branches
#
# Commits to `main` push builds to a `preview/main` branch:
#   pnpm install "mcansh/remix-testing-library#preview/main
#
# Can also be dispatched manually with base/installable branches to provide
# `experimental` branches from PRs or otherwise.

name: Preview Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      baseBranch:
        description: Base Branch
        required: true
      installableBranch:
        description: Installable Branch
        required: true

permissions:
  contents: write

concurrency:
  # Include `event_name` here because when a pull_request is merged (closed), the
  # `github.ref` goes back to `ref/heads/main` which will conflict with the run on
  # `main` from the merged PR
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    if: github.repository == 'mcansh/remix-testing-library'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (push)
        if: github.event_name == 'push'
        uses: actions/checkout@v6

      - name: Checkout (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.baseBranch }}

      - name: 🟧 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Vite+
        if: steps.changes.outputs.should_run == 'true'
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: Install dependencies
        if: steps.changes.outputs.should_run == 'true'
        run: vp install

      - name: Setup git
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

      # Build and force push over the preview/main branch
      - name: Build/push branch (push)
        if: github.event_name == 'push'
        run: |
          pnpm run setup-installable-branch preview/main
          git push --force --set-upstream origin preview/main
          echo "💿 pushed installable branch: https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

      # Build and normal push for experimental releases to avoid unintended force
      # pushes over remote branches in case of a branch name collision
      - name: Build/push branch (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          pnpm run setup-installable-branch ${{ inputs.installableBranch }}
          git push --set-upstream origin ${{ inputs.installableBranch }}
          echo "💿 pushed installable branch: https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
