name: 🦋 Changesets Release

on:
  push:
    branches:
      - release
      - "release-*"
      - "!release-experimental"
      - "!release-experimental-*"
      - "!release-manual"
      - "!release-manual-*"

permissions:
  id-token: write
  pull-requests: write
  contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 🦋 Changesets Release
    if: github.repository == 'mcansh/remix-testing-library'
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 🟧 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⚡️ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: ⚡️ Install Dependencies
        run: vp install

      - name: 🚀 PR / Publish
        uses: changesets/action@v1
        with:
          commit: "chore: Update version for release"
          title: "chore: Update version for release"
          publish: pnpm publish --access public
          createGithubReleases: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
